// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW_yMKxJXVKBj4mktPORFinJHM___W27c',
    appId: '1:144398668691:web:0e5afff9b283d1896e8e66',
    messagingSenderId: '144398668691',
    projectId: 'chatroom-ur',
    authDomain: 'chatroom-ur.firebaseapp.com',
    storageBucket: 'chatroom-ur.firebasestorage.app',
    measurementId: 'G-5028S4D95D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmiXRyDmcaFU0d_yGb0TvVlEJ-J8ZB6M',
    appId: '1:144398668691:android:af53c843f89793df6e8e66',
    messagingSenderId: '144398668691',
    projectId: 'chatroom-ur',
    storageBucket: 'chatroom-ur.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4akxBJcwoBcM4NTAFmoqZJ3-CQR9JsBU',
    appId: '1:144398668691:ios:5aa27275657d87b86e8e66',
    messagingSenderId: '144398668691',
    projectId: 'chatroom-ur',
    storageBucket: 'chatroom-ur.firebasestorage.app',
    iosBundleId: 'com.example.chatroomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4akxBJcwoBcM4NTAFmoqZJ3-CQR9JsBU',
    appId: '1:144398668691:ios:5aa27275657d87b86e8e66',
    messagingSenderId: '144398668691',
    projectId: 'chatroom-ur',
    storageBucket: 'chatroom-ur.firebasestorage.app',
    iosBundleId: 'com.example.chatroomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW_yMKxJXVKBj4mktPORFinJHM___W27c',
    appId: '1:144398668691:web:5fdf4b4edbacd10b6e8e66',
    messagingSenderId: '144398668691',
    projectId: 'chatroom-ur',
    authDomain: 'chatroom-ur.firebaseapp.com',
    storageBucket: 'chatroom-ur.firebasestorage.app',
    measurementId: 'G-5WYN4E6TDM',
  );
}
